//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_IP
    {
        public int ID { get; set; }
        public string DeviceName { get; set; }
        public string IP { get; set; }
        public string Netmask { get; set; }
        public string Place { get; set; }
        public string Annotation { get; set; }
    }
}
